version: '3'

services:

  nodejs-app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    image: shangavism/kube-jenkins-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: shangavism/kube-jenkins-db:latest
    ports:
      - "5432:5432"

